[package]
name = "auto_houses"
version = "0.1.0"
authors = ["K2Da <id.k2da@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = "0.6.2"
legion = "0.2.1"
